-- Autostart (exec-once)
hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("~/.config/scripts/hypr-monitors.py")
  hl.exec_cmd("swaync & hyprpaper & hypridle & udiskie &")
  hl.exec_cmd("~/.config/scripts/autostart.sh")
  hl.exec_cmd("~/.config/scripts/media-inhibit.sh &")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("hyprctl setcursor Colloid-dark-cursors 24")
  hl.exec_cmd("hyprctl dispatch 'hl.dsp.focus({ workspace = 1 })'")
end)
