layerrule = blur on, match:class ^(waybar|rofi|swaync-control-center|swaync-notification-window|logout_dialog)$
layerrule = ignore_alpha 0.5, match:class ^(waybar|rofi|swaync-control-center|swaync-notification-window|logout_dialog)$

# XDG DEKSTOP PORTAL GTK
windowrule {
    name = xdg-desktop-portal-gtk 
    match:class = .*xdg-desktop-portal-gtk.*
    float = true
    center = true
    pin = true
    size = 800 600
}

# Dialogs
windowrule {
    name = dialogs
    match:title = (.*Open.*|.*Save.*|.*wants to save.*|.*to open.*|.*Export.*|.*Select.*|.*Find.*|.*VLSub.*|.*Confirm.*|.*Print.*)
    float = true
    pin = true
    center = true
}

# Thunderbird
windowrule {
    name = thunderbird
    match:initial_title = Mozilla Thunderbird
	opacity = 0.9 0.9 1
}
windowrule {
    name =  thunderbird-write
    match:title = .*Write:.*
    float = true
    center = true
    size = 800 700
}

# kitty
windowrule {
    name = kitty
    match:class = .*kitty*
	opacity = 0.9 0.9 1
}


# # matrix lockscreen
windowrule {
    name = matrix
    match:title = MATRIXLOCK
	stay_focused = on
}

# VLC
windowrule {
    name = vlc
    match:class = vlc
	no_blur = true
	opaque = on
}

# Steam
windowrule {
    name = steam
    match:initial_class = steam
	no_blur = true
	opaque = on
    # float = true
    center = true
	idle_inhibit = always
}

# Bitwarden
windowrule {
    name = bitwarden
    match:initial_title = _crx_.*
    float = true
    pin = true
    center = true
	stay_focused = on
    size = 400 600
}

# Brasero
windowrule {
    name = brasero
    match:class = brasero
    float = true
    center = true
}

# ROG
windowrule {
    name = rog-control-center
    match:class = rog-control-center
    float = true
    center = true
    size = 950 600
}

# OpenRGB
windowrule {
    name = openrgb
    match:class = .*OpenRGB.*
    float = true
    center = true
    size = 950 600
}

# Frame Checker
windowrule {
    name = frame-checker
    match:class = Frame Checker
    float = true
    center = true
}

# Timeshift
windowrule {
    name = timeshift
    match:class = timeshift-gtk
    float = true
    center = true
}

# Gpic
windowrule {
    name = gpicview
    match:class = gpicview
    float = true
    center = true
    size = 1000 600
}

# Cameractrls
windowrule {
    name = cameractrls
    match:initial_title = Cameractrls
    float = true
    center = true
    size = 600 800
}

# Pavucontrol
windowrule {
    name = pavucontrol
    match:class = .*org.pulseaudio.pavucontrol.*
    float = true
    center = true
    pin = true
    size = 700 600
}

# Blueman Manager
windowrule {
    name = blueman-manager
    match:class = blueman-manager
    float = true
    center = true
    size = 700 600
}

# nwg-look
windowrule {
    name = nwg-look
    match:class = nwg-look
    float = true
    center = true
    size = 700 600
}

# nm-connection-editor
windowrule {
    name = nm-connection-editor
    match:class = nm-connection-editor
    float = true
    center = true
    size = 800 700
}

xwayland {
	force_zero_scaling = true
}

