return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",
  config = function()
    -- vim.filetype.add({
    -- extension = {
    -- },
    -- })
    vim.api.nvim_create_autocmd("FileType", {
      pattern = {
        "c",
        "cpp",
        "cmake",
        "comment",
        "css",
        "dosini",
        "go",
        "java",
        "javascript",
        "jsx",
        "json",
        "jsonc",
        "html",
        "hyprlang",
        "lua",
        "ledger",
        "markdown",
        "markdown_inline",
        "python",
        "rust",
        "ruby",
        "sshconfig",
        "scfg",
        "typescript",
        "tsx",
        "vim",
        "vue",
        "zsh",
        "bash",
        "sh",
        "yaml",
        "toml",
        "rasi",
      },
      callback = function()
        vim.treesitter.start() -- highlighting
        vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()" -- indentation
      end,
    })
    require("nvim-treesitter").install({
      "c",
      "cpp",
      "cmake",
      "comment",
      "css",
      "go",
      "java",
      "javascript",
      "jsx",
      "json",
      "json5",
      "html",
      "hyprlang",
      "lua",
      "ledger",
      "markdown",
      "markdown_inline",
      "python",
      "rust",
      "ruby",
      "scfg",
      "ssh_config",
      "typescript",
      "tsx",
      "vim",
      "vue",
      "zsh",
      "bash",
      "yaml",
      "toml",
      "rasi",
    })
  end,
}
